apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: afnf0igwo-java-quarkus
  janus-idp.io/tekton: afnf0igwo-java-quarkus
  backstage.io/kubernetes-id: afnf0igwo-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: afnf0igwo-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
